name: CI-Project-Check

# 1. Kiedy ma się uruchomić? (Przy każdym wypchnięciu kodu)
on: [push]

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      # 2. Pobierz kod z repozytorium na maszynę wirtualną GitHub
      - uses: actions/checkout@v3

      # 3. Sprawdź, czy Docker Compose poprawnie buduje obrazy
      - name: Build the Docker images
        run: docker-compose build
